query GetPlayerByCode($code: String) {
  getConnectCode(code: $code) {
    user {
      displayName
      connectCode {
        code
      }
      status
      rankedNetplayProfile {
        ratingOrdinal
        ratingUpdateCount
        wins
        losses
        continent
        characters {
          character
          gameCount
        }
      }
    }
  }
}