query GetPlayerById($id: String!) {
  getUser(fbUid: $id) {
    displayName
    connectCode {
      code
    }
    status
    rankedNetplayProfile {
      ratingOrdinal
      ratingUpdateCount
      wins
      losses
      continent
      characters {
        character
        gameCount
      }
    }
  }
}