name: update-leaderboard
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
jobs:
  update-leaderboard:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url '${{ secrets.API_UPDATE_URL }}' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET }}'